[project]
name = "causal-abstraction"
version = "0.0.0"
description = "A toolkit for causal analysis of artificial neural networks."
readme = "README.md"
requires-python = ">=3.10"
authors = [
    { name = "Atticus Geiger" }
]
dependencies = [
    "torch",
    "networkx",
    "matplotlib",
    "pandas",
    "numpy",
    "pyvene @ pyvene",
    "scikit-learn",
    "ipywidgets",
    "jupyterlab",
    "ipycytoscape",
    "seaborn",
    "transformers",
    "tensorboard",
    "dash",
    "dash-cytoscape",
    "jupyter-dash",
]

[project.optional-dependencies]
dev = [
    "pytest",
]

[tool.poetry]
name = "causal-abstraction"
version = "0.0.0"
description = "A toolkit for causal analysis of artificial neural networks."
authors = ["Atticus Geiger"]
readme = "README.md"
packages = [
    { include = "causal" },
    { include = "neural" },
    { include = "experiments" },
    { include = "tasks" }
]

[tool.poetry.dependencies]
python = "^3.10"
torch = "*"
networkx = "*"
matplotlib = "*"
pandas = "*"
numpy = "*"
pyvene = {git = "https://github.com/stanfordnlp/pyvene.git", branch = "main"}
scikit-learn = "*"
ipywidgets = "*"
jupyterlab = "*"
ipycytoscape = "*"
seaborn = "*"
transformers = "*"
tensorboard = "*"
dash = "*"
dash-cytoscape = "*"
jupyter-dash = "*"

[tool.poetry.group.dev.dependencies]
pytest = "*"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"